2025-10-19 17:37:59,917 - ERROR - Failed to load keys: HTTPConnectionPool(host='127.0.0.1', port=8201): Max retries exceeded with url: /v1/auth/token/lookup-self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E421FD8980>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-10-19 17:37:59,927 - INFO - Initialized with new local key
